language: node_js
node_js:
- '0.12'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GH_REF: TODO
  - secure: TODO
install:
- bash ./scripts/travis_install.sh
script:
- bash ./scripts/travis_script.sh
after_success:
- bash ./scripts/travis_after_success.sh
