# need sudo to remove yarn from path
# https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
sudo: required
dist: trusty

language: python
python: 3.6
cache:
  pip: true
  directories:
    - /home/travis/.yarn-cache/
matrix:
  include:
  - env: GROUP=js
  - env: GROUP=integrity
  - env: GROUP=python
  - env: GROUP=js_services
    python: 2.7
  - env: GROUP=python
    python: 3.5
  - env: GROUP=python
  - env: GROUP=js_cov
  - env: GROUP=cli
    python: 2.7
  - env: GROUP=cli
  - env: GROUP=docs
env:
  global:
    - GH_REF=github.com/jupyterlab/jupyterlab.git
    - YARN_CACHE_FOLDER=/home/travis/.yarn-cache/
    - secure: MWpTI6cj3/Bnmtrr0Oqlp2JeWqDneB9aEjlQDaRxLOkqVbxhqDcYW9qAgZZP+sq29vT5oVMWzyCirteKxJfG2vy3HQE1XNLhz82Sf/7sE6DQ51gohl0CcOeA/uA8hCXEw97hneFWsZgHKqSoch7nVDsE3qfYgO+930jHlnxYApJGP9hZFv2Q2NVa6+99kipEYS4BY/yBDYKy6/t4kXcnBrUlNaPtdjnXcrY9esLZ7EQtkaG5VqcQVIBaLJKGF5Q7Aufj5nCFaZ6hZDF1Bi/AbmIbVWFyiT+22i8DZK6YwenECckyzoWkl+bEhYepWsgBKh/BDgPBAmPWKHgU5V4apDaGqZBhF7FP6H02AdZYYuCwl47jyakqvWLZW7oDmorL+HsWG5HQ3m0tMT2ywdbwNOiD39tiPPXjsvROh5ys9vL6NzQvxILCeEOnzcZrFuxi2LGEZfnlqRIjkh1llUAvNc3mOycRLWDOwVQa2+U59qDRXCSY2RD+MOfcdFUGengVujTMaAPMBUa3E33/ZIOOKJtR5TIajYZvd9B2uDlz02QfvTK+hrTaNYJjRZ8WCaeSM/CIKdoLw+29MNO6eqtchw0/vNvM8c9EkhrhMQKcY04OecVhmZkemFhd4SD5l92VX3z3xSxLkmazfNkj3CigWDXNxfDd2ORoGjA46Pga8RM=
install:
- bash ./scripts/travis_install.sh
script:
- bash ./scripts/travis_script.sh
after_success:
- bash ./scripts/travis_after_success.sh
