language: node_js
node_js:
  - '0.12'
sudo: false
env: 
  matrix:
    - GROUP=
  global:
    - GH_REF: github.com/jupyter/jupyter-js-notebook.git
    - secure: "uTWpSYaQm9Iaieuw+Ym6Pw+OWTGLiH+gBI4T1YoE0M/6shP3Zec0X0MpOaHEYGXYHd+6uQgldQ7LTB7FZFV4H5jYgcIzhIN8P5lKfqxhROVIUdaZU93c2z2Zxyb+jipDEaYTHvAq138Dhlo8LZ/ESHMnZQDJ2eP0YzWcgIM4L60AutuGsEQZWf0Oz3UnSmk0Ccq7hUnYcBlM4+slfEbIKLiHYpATjgVLeDMSNkKMwiZ1/0rGP9uISaRfucYci5oZ5I9mCQ/RjxcwzRFDFLECt4ee6ygx6Odb0JFYC/OBi2ajsoULzV18/7IjAzMBtKx0RBD9AkaObitY1oOikGg0ZDSHtNqVJNT+CnBICCXhS95iCYffPCPEEs4v52l70PF77p9zsw3hpD4w8RpVQwSL+EdiVCxr5K9sXK2FaARCyUOpiklKFfz9hq90v/ehfk72agr8MLMTKJGoazHZ1rKFimAa4cDkIZys9bSKc4X5LGI9kJRF1bM2mb+G168Cwpyu4gWnCceDPENIKQ7fXPojTvwkAUhblG/eJcn2SUR/ULOYxWJw/AhM+CGf1/LyuGXzc0uZ+ZxrPI/Lvp8JkHLLUjNn6dgR7j3r0Ghu1ly4BMHpt5DgQP/N/f5V9Sw3sXUSZvg06UffDAcnxZUYCrQgGpm9lDPkJvk+5/dfuHmQoy8="
install:
  - bash ./scripts/travis_install.sh
script:
  - bash ./scripts/travis_script.sh
after_success:
  - bash ./scripts/travis_after_success.sh
