
name: jupyterlab_documentation
channels:
  - conda-forge
dependencies:
- python=3.8
- sphinx>=1.8
- sphinx-copybutton
- sphinx_rtd_theme
- recommonmark
- pytest
- pip
- nodejs
- pip:
  - jsx-lexer
  - pytest-check-links[cache]>=0.4.3
  - requests_cache
