name: jupyterlab-dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  # runtimes
  - nodejs >=18,<19
  - python >=3.11,<3.12
  # package managers
  - pip
  - yarn <2
  # build
  - hatch-jupyter-builder >=0.3.2
  - hatchling >=1.5.0
  # run
  - async-lru >=1.0.0
  - ipykernel
  - jinja2 >=3.0.3
  - jupyter_core
  - jupyter_server >=2.0.1,<3
  - jupyter-lsp >=1.5.1
  - jupyterlab_server >=2.19.0,<3
  - notebook-shim >=0.2
  - packaging
  - tornado >=6.2.0
  - traitlets
  # test
  - coverage
  - pytest >=7.0
  - pytest-check-links >=0.7
  - pytest-console-scripts
  - pytest-cov
  - pytest-jupyter-server >=0.5.3
  - pytest-timeout
  - pytest-tornasync
  - requests
  - requests-cache
  - virtualenv
  # dev
  - black-jupyter
  - bump2version
  - hatch
  - pre-commit
  - pytest-cov
  - python-build
  - ruff
  # demo
  - jupyter-server-proxy
  - jupyterlab-link-share >=0.2
  - matplotlib-base
  - numpy
  - vega_datasets
  - xeus-python
  # extra conda stuff
  - jsonschema-with-format-nongpl
  - pip:
    - jupyter-collaboration >=1.0.0a1
