# This action automatically schedules issues to be closed that have been
# labeled as answered if there is no activity on them for 30 days. This takes
# care of the common usecase of an issue being answered to the best of our
# ability and no other follow-up from the submitter.
name: 'Close answered issues'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          days-before-pr-stale: -1
          days-before-pr-close: -1
          days-before-issue-stale: 7
          days-before-issue-close: 5
          stale-issue-label: 'status:Closing as Answered'
          only-issue-labels: 'status:Answered'
