name: Docker Tests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker:
    name: Docker Dev Container
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the image
        run: |
          bash ./docker/start.sh build
          docker image ls 2>&1 | grep -ie "jupyterlab_dev" -

      - name: Start the dev container
        run: |
          bash ./docker/start.sh dev-detach

      - name: Wait for JupyterLab
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8888/
          timeout: 360000
