name: Pull Request Labeler
# This workflow is supposed to run every 5 minutes
on:
  schedule:
    - cron: '*/20 * * * *'
permissions:
  pull-requests:
    write
jobs:
  triage:
    name: Update PR Labels
    runs-on: ubuntu-20.04
    steps:
      - if: github.repository == 'jupyterlab/jupyterlab'
        uses: paulfantom/periodic-labeler@dffbc90404f371f76444a69221c2f7ad079e2319
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler.yml
