name: Fix License Headers

on:
  pull_request_target:

jobs:
  header-license-fix:
    runs-on: ubuntu-20.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git to use https
        run: git config --global hub.protocol https

      - name: Checkout the branch from the PR that triggered the job
        run: hub pr checkout ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix License Header
        uses: apache/skywalking-eyes/header@v0.4.0
        with:
          mode: fix

      - name: Commit any changes
        shell: bash -l {0}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git pull --no-tags
          git add *
          git commit --allow-empty -m "Automatic application of license header"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get modified files
        id: changed-files
        uses: tj-actions/changed-files@v34.5.3
        with:
          base_sha: 'HEAD~1'
          sha: 'HEAD'

      - name: Push fixes
        if: steps.changed-files.outputs.any_changed == 'true'
        shell: bash -l {0}
        run: |
          echo "Changed files"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "  $file"
          done
          git diff HEAD~1

          git config push.default upstream
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
