name: Linux JS Tests

on:
  push:
    branches: [3.6.x]
  pull_request:
    branches: [3.6.x]
  release:
    types: [published]

jobs:
  linuxjs:
    name: JS
    strategy:
      matrix:
        group:
          [
            js-application,
            js-cells,
            js-cell-toolbar,
            js-codeeditor,
            js-codemirror,
            js-collaboration,
            js-completer,
            js-console,
            js-coreutils,
            js-csvviewer,
            js-debugger,
            js-docmanager,
            js-docregistry,
            js-documentsearch,
            js-filebrowser,
            js-fileeditor,
            js-imageviewer,
            js-inspector,
            js-logconsole,
            js-mainmenu,
            js-nbformat,
            js-notebook,
            js-observables,
            js-outputarea,
            js-rendermime,
            js-settingregistry,
            js-statedb,
            js-statusbar,
            js-terminal,
            js-toc,
            js-translation,
            js-ui-components,
            js-testutils,
          ]
      fail-fast: false
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        env:
          GROUP: ${{ matrix.group }}
        run: |
          bash ./scripts/ci_install.sh

      - name: Run test ${{ matrix.group }}
        env:
          GROUP: ${{ matrix.group }}
        run: |
          bash ./scripts/ci_script.sh
