name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add conda to $PATH
      run: echo ::add-path::$CONDA/condabin

    - name: Update conda
      run: conda update -y -n base conda setuptools

    - name: Init conda
      run: |
        conda init bash
        conda info -a
    - name: Create the conda environment
      run: conda create -n jupyterlab-debugger --yes --quiet -c conda-forge nodejs jupyterlab=2 xeus-python=0.7.1 ptvsd python=$PYTHON_VERSION
      env:
        PYTHON_VERSION: '3.8'

    - name: Build and install the extension
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate jupyterlab-debugger
        jlpm && jlpm run build
        jupyter labextension link .

    - name: Browser check
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate jupyterlab-debugger
        python -m jupyterlab.browser_check

    - name: Run the tests
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate jupyterlab-debugger
        export XEUS_LOG=1
        jlpm run test
