name: Windows Tests

on:
  push:
    branches: [3.5.x]
  pull_request:
    branches: [3.5.x]
  release:
    types: [published]

jobs:
  windowstests:
    name: Windows
    strategy:
      matrix:
        group: [integrity, python]
      fail-fast: false
    runs-on: windows-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        env:
          GROUP: ${{ matrix.group }}
        run: .\scripts\ci_install
        shell: pwsh

      - name: Run test ${{ matrix.group }}
        env:
          GROUP: ${{ matrix.group }}
        run: .\scripts\ci_script
        shell: pwsh
